# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *


class SubWindow(QMainWindow):
    def __init__(self):
        super(SubWindow, self).__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.showMaximized()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 10, 2540, 1000))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table.setFont(font)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.table.verticalHeader().setVisible(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(640, 1050, 220, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.submit.setFont(font)
        self.submit.setObjectName("submit")
        self.addrow = QtWidgets.QPushButton(self.centralwidget)
        self.addrow.setGeometry(QtCore.QRect(890, 1050, 220, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.addrow.setFont(font)
        self.addrow.setObjectName("addrow")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(1370, 1050, 220, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.delbut = QtWidgets.QPushButton(self.centralwidget)
        self.delbut.setGeometry(QtCore.QRect(1620, 1050, 220, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.delbut.setFont(font)
        self.delbut.setObjectName("delbut")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1250, 1050, 161, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DBController"))
        self.submit.setText(_translate("MainWindow", "輸入"))
        self.addrow.setText(_translate("MainWindow", "新增列"))
        self.delbut.setText(_translate("MainWindow", "刪除"))
        self.label.setText(_translate("MainWindow", "編號"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = SubWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
